### ISSUE TITLE
package2readme() fails with mrremind

### ISSUE THREAD

**Issue by orichters** [pik-piam/lucode2#60] opened 2022-01-04 18:04 UTC
As already noticed beginning of December in [madrat-verse on mattermost](https://mattermost.pik-potsdam.de/rd3/channels/madrat-verse/cc1bp5rx57dndj5am3khku5pxh), `lucode2::buildLibrary()` does not update the readme-file of `mrremind` anymore. Running `lucode2::package2readme()` alone (a suggested workaround) from `mrremind` directory yields:
```
Error in file(con, "r") :
  cannot open the connection to 'https://pik-piam.r-universe.dev/packages'
```
The command with the error is in [line 105](https://github.com/pik-piam/lucode2/blob/master/R/package2readme.R#L105):
```
readLines("https://pik-piam.r-universe.dev/packages")
```
The problem appears to be the https: `'Peer certificate cannot be authenticated with given CA certificates'`. Changing the URL to http avoids it. Would be great if this was fixed.

**Comment by pfuehrlich-pik** [comment] 2022-01-05 11:50
I cannot reproduce this, buildLibrary works fine for mrremind on my laptop

**Comment by orichters** [comment] 2022-01-05 13:25
confirm that it works on my laptop, but not on the cluster.

**Comment by tscheypidi** [comment] 2022-01-05 13:35
I just tested in on the cluster and it was working for me. Did you perhaps try it on one of the compute nodes (e.g. via submitting a slurm job)? This would not work as the compute nodes don't have internet access, but the login nodes have.

**Comment by tscheypidi** [comment] 2022-01-05 13:56
ah ok, sorry...I was not aware of that. Perhaps the problem was solved by the IT in the meantime (otherwise I could not explain why it works in my case)?

In any case I will close this issue now as it is related to the cluster and not to `lucode2`.

**Closed by tscheypidi** 2022-01-05 13:56 UTC
